[project]
name = "huggingface-trainer"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "huggingface-hub~=0.28.1",
    "keras~=2.15.0",
    "numpy~=1.26.4",
    "pandas~=2.2.3",
    "tensorflow-cpu~=2.15.1",
    "tensorflow-io-gcs-filesystem==0.31.0",
    "transformers~=4.40.2",
]
